name: tests

on:
  push:
      branches:
        - '*'
  pull_request:

jobs:
  tests:

    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v5.6.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Run tests
        uses: burrunan/gradle-cache-action@v3.0.2
        with:
          arguments: check --no-daemon
